name = "Myriad"
author = "Ayes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d00335c2d3d944577b8933b3885c8e938e9861a9dc949a576695be87ba3faefe"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
