name = "Myriad"
author = "Ayes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e35cd9db49e1c8e05738d3f9096353b2c0ed578f179061464c7a4c6ea08bd75e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
