name = "Myriad"
author = "Ayes"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ab74d24a9060a60b230e45b620b6e61cd5dda25462160a865790ade9505f809"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
